<?xml version="1.0" encoding="utf-8"?><Database Name="QL_SHOP1" Class="QLShopDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=HUY;Initial Catalog=QL_SHOP1;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QL_SHOP1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PHANQUYEN" Member="PHANQUYENs">
    <Type Name="PHANQUYEN">
      <Column Name="MaQuyen" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenQuyen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="PHANQUYEN_TAIKHOAN" Member="TAIKHOANs" ThisKey="MaQuyen" OtherKey="MaQuyen" Type="TAIKHOAN" />
    </Type>
  </Table>
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="TenTK" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gmail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MaQuyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Pass" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TAIKHOAN_HOADON" Member="HOADONs" ThisKey="TenTK" OtherKey="TenTK" Type="HOADON" />
      <Association Name="PHANQUYEN_TAIKHOAN" Member="PHANQUYEN" ThisKey="MaQuyen" OtherKey="MaQuyen" Type="PHANQUYEN" IsForeignKey="true" />
      <Association Name="PHANQUYEN1_TAIKHOAN" Member="PHANQUYEN1" ThisKey="MaQuyen" OtherKey="MaQuyen" Type="PHANQUYEN1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOAI" Member="LOAIs">
    <Type Name="LOAI">
      <Column Name="MaLoai" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LOAI_SANPHAM" Member="SANPHAMs" ThisKey="MaLoai" OtherKey="MaLoai" Type="SANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.PHANQUYEN" Member="PHANQUYEN1s">
    <Type Name="PHANQUYEN1">
      <Column Name="MaQuyen" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenQuyen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="PHANQUYEN1_TAIKHOAN" Member="TAIKHOANs" ThisKey="MaQuyen" OtherKey="MaQuyen" Type="TAIKHOAN" />
    </Type>
  </Table>
  <Table Name="dbo.SANPHAM" Member="SANPHAMs">
    <Type Name="SANPHAM">
      <Column Name="MaSP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DoiTuong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gia" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="MaLoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Images" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="SANPHAM_CT_HOADON" Member="CT_HOADONs" ThisKey="MaSP" OtherKey="MaSP" Type="CT_HOADON" />
      <Association Name="LOAI_SANPHAM" Member="LOAI" ThisKey="MaLoai" OtherKey="MaLoai" Type="LOAI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="MaHD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTK" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="NgayDat" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ngaygiao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="HOADON_CT_HOADON" Member="CT_HOADONs" ThisKey="MaHD" OtherKey="MaHD" Type="CT_HOADON" />
      <Association Name="TAIKHOAN_HOADON" Member="TAIKHOAN" ThisKey="TenTK" OtherKey="TenTK" Type="TAIKHOAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CT_HOADON" Member="CT_HOADONs">
    <Type Name="CT_HOADON">
      <Column Name="MaHD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="HOADON_CT_HOADON" Member="HOADON" ThisKey="MaHD" OtherKey="MaHD" Type="HOADON" IsForeignKey="true" />
      <Association Name="SANPHAM_CT_HOADON" Member="SANPHAM" ThisKey="MaSP" OtherKey="MaSP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
</Database>